require:
  - rubocop-sorbet

Naming/FileName:
  Exclude:
    - "Casks/*"

Style/FrozenStringLiteralComment:
  Exclude:
    - "Casks/*"

Sorbet/FalseSigil:
  Exclude:
    - "Casks/*"

Metrics/MethodLength:
  Max: 20
