require:
  - rubocop-sorbet

Naming/FileName:
  Exclude:
    - "Casks/*"

Sorbet/FalseSigil:
  Exclude:
    - "Casks/*"

Style/FrozenStringLiteralComment:
  Exclude:
    - "Casks/*"

Style/StringLiterals:
  Exclude:
    - "Casks/*"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/MethodLength:
  Max: 20
