require:
  - rubocop-sorbet

AllCops:
  Exclude:
    - "Casks/*"
    - "Formula/*"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/MethodLength:
  Max: 20
