name: Updater
on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'

jobs:
  update:
    name: Update
    runs-on: macos-latest
    steps:
      - name: Update Homebrew
        run: |
          brew update --quiet
          brew install coreutils

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Move repo
        run: |
          mkdir -p /usr/local/Homebrew/Library/Taps/jat001
          mv "$GITHUB_WORKSPACE" /usr/local/Homebrew/Library/Taps/jat001/homebrew-ox
          ln -s /usr/local/Homebrew/Library/Taps/jat001/homebrew-ox "$GITHUB_WORKSPACE"

      - name: Update version
        run: |
          cd "$(brew --repo jat001/ox)"
          ./bin/update_version.sh --push

      - name: Update readme
        run: |
          cd "$(brew --repo jat001/ox)"
          bundle install
          ./bin/update_readme.rb --push
