name: Updater
on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'

jobs:
  update:
    name: Update
    runs-on: macos-latest
    steps:
      - name: Tap repo
        run: |
          brew update --quiet
          brew tap jat001/ox

      - name: Update version
        run: |
          cd "$(brew --repo jat001/ox)"
          ./bin/update_version.sh --push

      - name: Update readme
        run: |
          cd "$(brew --repo jat001/ox)"
          bundle install
          ./bin/update_readme.rb --push
